export const arrayOfAvatar = [
    { id: 7, uri: 'https://randomuser.me/api/portraits/men/2.jpg', name: 'Marc Smith' },
  { id: 1, uri: 'https://randomuser.me/api/portraits/women/1.jpg', name: 'Laura Dillard' },
  { id: 6, uri: 'https://randomuser.me/api/portraits/men/1.jpg', name: 'John Doe' },
  { id: 2, uri: 'https://randomuser.me/api/portraits/women/2.jpg', name: 'Lenna Pajocko' },
  { id: 9, uri: 'https://randomuser.me/api/portraits/men/4.jpg', name: 'David Lee' },
  { id: 10, uri: 'https://randomuser.me/api/portraits/men/5.jpg', name: 'Alex Taylor' },
  { id: 3, uri: 'https://randomuser.me/api/portraits/women/3.jpg', name: 'Sophie Martin' },
  { id: 4, uri: 'https://randomuser.me/api/portraits/women/4.jpg', name: 'Emma Wilson' },
  { id: 5, uri: 'https://randomuser.me/api/portraits/women/5.jpg', name: 'Julie Brown' },
  { id: 8, uri: 'https://randomuser.me/api/portraits/men/3.jpg', name: 'Paul Johnson' },
];

export const feedPosts = [
  {
    id: 1,
    userId: 1,
    userName: 'Laura Dillard',
    userAvatar: 'https://randomuser.me/api/portraits/women/1.jpg',
    image: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=500',
    likes: 234,
    time: '2 min ago',
  },
  {
    id: 2,
    userId: 2,
    userName: 'Lenna Pajocko',
    userAvatar: 'https://randomuser.me/api/portraits/women/2.jpg',
    image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=500',
    likes: 892,
    time: '5 min ago',
  },
  {
    id: 3,
    userId: 6,
    userName: 'John Doe',
    userAvatar: 'https://randomuser.me/api/portraits/men/1.jpg',
    image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?w=500',
    likes: 456,
    time: '10 min ago',
  },
  {
    id: 4,
    userId: 3,
    userName: 'Sophie Martin',
    userAvatar: 'https://randomuser.me/api/portraits/women/3.jpg',
    image: 'https://images.unsplash.com/photo-1470770903676-69b98201ea1c?w=500',
    likes: 678,
    time: '15 min ago',
  },
  {
    id: 5,
    userId: 7,
    userName: 'Marc Smith',
    userAvatar: 'https://randomuser.me/api/portraits/men/2.jpg',
    image: 'https://images.unsplash.com/photo-1501594907352-04cda38ebc29?w=500',
    likes: 1203,
    time: '20 min ago',
  },
];